services:
  real_time_digits_backend:
    container_name: real_time_digits_backend
    build:
      context: .
    volumes:
      - ./real_time_digits:/home/task_app/real_time_digits
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - real_time_digits_redis

  real_time_digits_redis:
    image: redis:alpine
    container_name: real_time_digits_redis